version: '3.1'

services:
  db:
    image: postgres:13.4
    restart: always
    command: postgres -c 'max_connections=1000'
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: 'asdf'
    volumes:
      - ./src/main/resources/db/:/docker-entrypoint-initdb.d/
